drop schema if exists microservices_prod_hierarchy;
create schema microservices_prod_hierarchy;

use microservices_prod_hierarchy;


DROP TABLE IF EXISTS PRIMARY_PROD_CATEGORY;
CREATE TABLE IF NOT EXISTS PRIMARY_PROD_CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(200) NOT NULL
);


DROP TABLE IF EXISTS SECONDARY_PROD_CATEGORY;
CREATE TABLE IF NOT EXISTS secondary_prod_category (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(200) NOT NULL,
    PRIMARY_CATEGORY_ID BIGINT NOT NULL,
    FOREIGN KEY (PRIMARY_CATEGORY_ID)
        REFERENCES PRIMARY_PROD_CATEGORY(ID)
);


DROP TABLE IF EXISTS TERTIARY_PROD_CATEGORY;
CREATE TABLE IF NOT EXISTS TERTIARY_PROD_CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(200) NOT NULL,
    SECONDARY_CATEGORY_ID BIGINT NOT NULL,
    FOREIGN KEY (SECONDARY_CATEGORY_ID)
        REFERENCES SECONDARY_PROD_CATEGORY (ID)
);


DROP TABLE IF EXISTS CLOTHING_PRODUCTS;
CREATE TABLE IF NOT EXISTS CLOTHING_PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    QUANTITY_AVAILABLE BIGINT NOT NULL,
    UNIT_PRICE DOUBLE(10,4),
    CATEGORY_ID BIGINT NOT NULL,
    BRAND_NAME VARCHAR(200)  NOT NULL,
    SIZE VARCHAR(200),
    PRODUCT_DETAILS VARCHAR(500),    
    FOREIGN KEY (CATEGORY_ID)
        REFERENCES TERTIARY_PROD_CATEGORY(ID)
);

commit;


INSERT INTO PRIMARY_PROD_CATEGORY(CATEGORY_NAME) VALUES('Men');
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Topwear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Men'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('T-Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Casual Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Formal Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sweaters & Sweatshirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jackets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Blazers & Coats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Suits',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Clothing Fabric',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jeans',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Casual Trousers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Formal Trousers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shorts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Track Pants/Joggers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Topwear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Sports & Active Wear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Men'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Active T-Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Track Pants & Shorts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jackets & Sweatshirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Swimwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Smart Wearables',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Accessories',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Equipment',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Kurtas & Kurta Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sherwanis',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Nehru Jackets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Dhoti',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Sports & Active Wear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Innerwear & Sleepwear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Men'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Briefs & Trunks',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Boxers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Vests',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sleepwear & Loungewear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Thermals',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Casual Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Formal Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sandals & Floaters',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Flip Flops',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Customizable Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Socks',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Innerwear & Sleepwear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Sunglasses and Frames',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Men'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Fashion Accessories',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Men'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Wallets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Belts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Ties, Cufflinks & Pocket Squares',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Accessory Gift Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Helmets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Caps & Hats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Mufflers, Scarves & Gloves',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Phone Cases',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Travel Accessories',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Rings & Wristwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Fashion Accessories'));
INSERT INTO PRIMARY_PROD_CATEGORY(CATEGORY_NAME) VALUES('Women');
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Indian & Fusion Wear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Women'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Kurtas & Suits',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Kurtis, Tunics & Tops',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Ethnic Dresses',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Leggings, Salwars, Churidars',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Skirts & Palazzos',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sarees & Blouses',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Dress Material',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Lehenga Choli',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Dupattas & Shawls',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jackets & Waistcoats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Indian & Fusion Wear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Western Wear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Women'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Dresses & Jumpsuits',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tops, T-Shirts & Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jeans & Jeggings',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Trousers & Capris',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shorts & Skirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shrugs',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sweaters & Sweatshirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jackets & Waistcoats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Coats & Blazers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bras & Lingerie Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Briefs',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shapewear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sleepwear & Loungewear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Swimwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Camisoles & Thermals',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Western Wear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Footwear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Women'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Flats & Casual Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Heels',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Boots',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Shoes & Floaters',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Clothing',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Footwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Accessories',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Equipment',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Footwear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Headphones & Speakers',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Women'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Makeup',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Skincare',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Premium Beauty',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Fragrances',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Fashion Jewellery',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Fine Jewellery',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Headphones & Speakers'));
INSERT INTO PRIMARY_PROD_CATEGORY(CATEGORY_NAME) VALUES('Kids');
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Boys Clothing',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Kids'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('T-Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jeans & Trousers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Shorts & Dungarees',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Track Pants & Pyjamas',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Clothing Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Indian Wear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sweaters, Sweatshirts & Jackets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Rompers & Sleepwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Boys Clothing'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Girls Clothing',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Kids'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Dresses',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tops & T-Shirts',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Clothing Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Indian Wear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Skirts, Shorts & Jumpsuits',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tights & Leggings',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jeans, Trousers & Capris',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Track Pants',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sweaters, Sweatshirts & Jackets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Rompers & Sleepwear',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Casual Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sandals',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Flip flops',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Clothing'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Girls Footwear',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Kids'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Casual Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Flats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Heels',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sports Shoes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Flip flops',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sandals',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bags & Backpacks',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Watches',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Jewellery',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Hair Accessories',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sunglasses',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Frames',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Girls Footwear'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Brands',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Kids'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Mothercare',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Gini and Jony',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('U.S. Polo Assn. Kids',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('United Colors of Benetton',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('YK',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Allen Solly Junior',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Next',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Pepe Jeans',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tommy Hilfiger',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('612 League',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Action Figures & Soft Toys',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Learning & Development Toys',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Toy Vehicles',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Activity & Construction Toys',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Musical Toys & Ride Ons',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Kids' ) ));
INSERT INTO PRIMARY_PROD_CATEGORY(CATEGORY_NAME) VALUES('Home & Living');
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Bed Linen & Furnishing',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Home & Living'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bedsheets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bedding Sets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Blankets Quilts and Dohars',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Pillows & Pillow Covers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bed Covers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bath Towels',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Hand and Face Towels',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Beach Towels',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Towels Set',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bath Rugs',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bath Robes',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bathroom Accessories',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Bed Linen & Furnishing'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Cushions & Cushion Covers',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Home & Living'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Carpets',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Floor Mats and Dhurries',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Door Mats',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tableware & Serveware',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Cookware & Kitchen Tools',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Kitchen Storage',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Table Covers & Furnishings',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Cushions & Cushion Covers'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Home Décor',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Home & Living'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Plants & Planters',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Aromas, Candles & Candle Holders',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Clocks',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Mirrors',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Wall Décor',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Wall Shelves',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Fountains',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Showpieces & Vases',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Floor lamps',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Table lamps',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Wall lamps',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Organisers',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Hooks & Holders',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Home Décor'));
INSERT INTO SECONDARY_PROD_CATEGORY(CATEGORY_NAME,PRIMARY_CATEGORY_ID) VALUES('Brands',(select ID from PRIMARY_PROD_CATEGORY where CATEGORY_NAME='Home & Living'));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Bombay Dyeing',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Spaces',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Portico New York',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Pure Home & Living',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Swayam',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Raymond Home',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('At Home by Nilkamal',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Corelle',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Trident',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Cortina',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('WELHOME',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Random',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Home sparkle',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Tangerine',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('Sej by Nisha Gupta',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
INSERT INTO TERTIARY_PROD_CATEGORY(CATEGORY_NAME,SECONDARY_CATEGORY_ID) VALUES('House This',(select ID from SECONDARY_PROD_CATEGORY where CATEGORY_NAME='Brands' and primary_category_id =(select id from primary_prod_category where category_name='Home & Living' ) ));
commit;
