CREATE SCHEMA microservices_prod;

USE microservices_prod;

DROP TABLE IF EXISTS unit_type;
CREATE TABLE IF NOT EXISTS unit_type(ID BIGINT AUTO_INCREMENT PRIMARY KEY, UNIT_NAME VARCHAR(200) NOT NULL);

DROP TABLE IF EXISTS categories;
CREATE TABLE IF NOT EXISTS categories (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(200) NOT NULL,
    unit_type_ID BIGINT NOT NULL,
    CONTROLLED BOOLEAN,
    FOREIGN KEY (unit_type_ID)
        REFERENCES unit_type (ID)
);

SELECT * FROM categories;

DROP TABLE IF EXISTS inventory;
CREATE TABLE IF NOT EXISTS inventory (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    UNIT_PRICE DOUBLE(10,4),
    PURCHASE_PRICE DOUBLE(10,4),
    TAX_RATE INTEGER(99),
    CATEGORY_ID BIGINT NOT NULL,
    BRAND_NAME VARCHAR(200),
    FOREIGN KEY (CATEGORY_ID)
        REFERENCES categories (ID)
);