CREATE SCHEMA microservices_invoice;

USE microservices_invoice;

DROP TABLE IF EXISTS mode_of_pay;
CREATE TABLE IF NOT EXISTS mode_of_pay (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MODE_NAME VARCHAR(100) NOT NULL,
    MODE_DESC VARCHAR(500)
);

DROP TABLE IF EXISTS invoice;
CREATE TABLE IF NOT EXISTS invoice (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUST_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    QUANTITY INTEGER(5),
    DATE_OF_PURCHASE DATETIME,
    MODE_PAY_ID BIGINT NOT NULL,
    TAX_AMT INTEGER,
    CASHIER_NAME VARCHAR(500),
    FOREIGN KEY (MODE_PAY_ID)
        REFERENCES invoice (ID)
);


